### ISSUE TITLE
Improve file opening performance

### ISSUE THREAD

**Issue by JanSimek** [nextgeniuspro/vfspp#10]
With the current implementation of `OpenFile` it can take up to several milliseconds to retrieve a file from VFS on my system.

The performance can be drastically improved by switching the container of `TFileList` from `set` to `unordered_map` and using the path as key:

```cpp
IFilePtr FindFile(const FileInfo& fileInfo, const TFileList& fileList) const
{
   auto it = fileList.find(fileInfo.AbsolutePath());

   if (it == fileList.end()) {
      return nullptr;
   }
   return it->second;
}
```

In my application, I have to go through >3000 files during the start-up and the above change improves starting time from ~20 seconds to sub 1 second.

PS: thank you for sharing such a useful project! It is amazing and straightforward to extend with a custom driver

**Comment by nextgeniuspro** [comment]
Hi @JanSimek,

Pushed commit with such fix. Thank you very much for an idea
