### ISSUE TITLE
Non-existing file is returned from the first NativeFileSystem even if it exists in another

### ISSUE THREAD

**Issue by JanSimek** [nextgeniuspro/vfspp#11]
To reproduce, create two native filesystem mounts and add a test file into the second one:

```bash
mkdir -p /home/user/test/fs1
mkdir -p /home/user/test/fs2
echo "Hello World" > /home/user/test/fs2/test.txt
```

Notice that we initialize fs1 first and we want to open the file as read-only:

```c++
    VirtualFileSystemPtr vfs(new VirtualFileSystem());

    auto native1 = std::make_unique<NativeFileSystem>("/home/user/test/fs1");
    auto native2 = std::make_unique<NativeFileSystem>("/home/user/test/fs2");

    native1->Initialize();
    native2->Initialize();

    vfs->AddFileSystem("/", std::move(native1));
    vfs->AddFileSystem("/", std::move(native2));

    auto file = vfs->OpenFile(FileInfo("/test.txt"), IFile::FileMode::Read);
    if (!file->IsOpened()) {
        throw std::runtime_error("not opened");
    }
```

In the `NativeFileSystem` there is this piece of code that returns a new file and thus prevents the second filesystem from being checked for the presence of a real file:

https://github.com/nextgeniuspro/vfspp/blob/master/include/vfspp/NativeFileSystem.hpp#L276-L289

**Comment by JanSimek** [comment]
Perhaps, the fix might be to check `requestWrite` before returning a new file?

```c++
        if (!isExists && (!IsReadOnlyST() && requestWrite)) {
            mode = mode | IFile::FileMode::Truncate;
            file.reset(new NativeFile(filePath));
        }
```

**Comment by nextgeniuspro** [comment]
Hi @JanSimek,

Thanks for the report. Yes, it's an issue and will be fixed soon. Overall, it's an unfinished 'patching' feature that allow to mount several FS to the same alias and merge files from all attached FS into one virtual.

**Comment by nextgeniuspro** [comment]
I've also pushed fix with the 'patching/dlc' feature, check it please if it solves your issue
