### ISSUE TITLE
[Linux] Support for GCC compiler?

### ISSUE THREAD

**Issue by rilpires** [nextgeniuspro/vfspp#5]
Looks like CMake sets these flags for compiling:
`set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++11 -stdlib=libc++ -fno-rtti -fno-exceptions -g -Wall")`
For what I [found](https://stackoverflow.com/a/24419967/10508429), this option `-stdlib=libc++` is only supported in clang. I'd really like to have a unique compiler for my project... Should I expect unexpected behavior if I remove this flag?

**Comment by nextgeniuspro** [comment]
thx, fixed
